stages:
  - test
  - build
  - deploy

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]

test:
  image: node:14
  stage: test
  script:
    - cd server
    - npm install
    - npx jest


  

# Frontend build job
build_frontend:
  image: node:18.18.0
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

build_backend:
  image: node:18.18.0
  stage: build
  script:
    - cd server
    - npm install
    # - npm run build
  artifacts:
    paths:
      - server/


# Frontend deploy job

deploy:
  image: node:18.18.0
  stage: deploy
  script:
    - chmod 400 "${SSH_PRIVATE_KEY}"
    - scp -o StrictHostKeyChecking=no -i "${SSH_PRIVATE_KEY}" -r build/* student@csci5308vm23.research.cs.dal.ca:~/frontend
    - ssh -o StrictHostKeyChecking=no -i "${SSH_PRIVATE_KEY}" student@csci5308vm23.research.cs.dal.ca "pm2 serve ~/frontend 80 --spa --name 'frontend' > frontend.log 2>&1 &"

# Backend deploy job
deploy_backend:
  image: node:18.18.0
  stage: deploy
  script:
    - chmod 400 "${SSH_PRIVATE_KEY}"
    - scp -o StrictHostKeyChecking=no -i "${SSH_PRIVATE_KEY}" -r server/* student@csci5308vm23.research.cs.dal.ca:~/backend
    - ssh -o StrictHostKeyChecking=no -i "${SSH_PRIVATE_KEY}" student@csci5308vm23.research.cs.dal.ca "cd ~/backend && npm install && pm2 start index.js --name 'backend' > backend.log 2>&1 &"
