stages:
  - build
  # - test
  - deploy

build:
  image: node:18.18.0
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

# test:
#   image: node:18.18.0
#   stage: test
#   script:
#     - npm install
#     - npx jest

deploy:
  image: node:18.18.0
  stage: deploy
  script:
    - chmod 400 "${SSH_PRIVATE_KEY}"
    - scp -o StrictHostKeyChecking=no -i "${SSH_PRIVATE_KEY}" -r build/* student@csci5308vm23.research.cs.dal.ca:~/frontend
    - ssh -o StrictHostKeyChecking=no -i "${SSH_PRIVATE_KEY}" student@csci5308vm23.research.cs.dal.ca "cd ~/frontend && serve -s . > webserver.log 2>&1 &"


